id: P7676A9ED
initial_creation_type: input
source_metadata:
  title: Katok Dampa Deshek Series
  language: es
  description: 'Texts by Katok Dampa Deshek (kaḥ thog dam pa bde gshegs, 1122–1192),
    the founder of Katok Monastery:'
  volume:
    b1c753f0929c487a9bb0235a1afb34f7:
      title: The Last Testament of Katok Dampa Deshek
      parent: Last Testament
created_at: '2022-03-01T00:13:09.690139'
last_modified_at: '2022-03-01T00:13:09.690142'
